[general]
documents_per_page = 20

[logging]
file = "application.log"
level = "debug"

[session]
ttl = "90 00:00:00" # 90 days
cookie = "_simwatch_api_session_id"

[database]
uri = "mongodb://localhost:27017/simwatch_api"
timeout = 1.1 # 1.1 seconds

[queue]
type = "mongo"

[mongo_queue]
tasks_collection = "simwatch_api_tasks"
keep_done_tasks_for = "90 00:00:00" # 90 days
cleanup_interval = "01:00:00" # 1 hour

[grpc]
socket = "localhost:12000"
